spring:     
  application: 
    name: demo 

  datasource:
    url: jdbc:h2:mem:demo
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    

  h2:
    console:
      enabled: true
    
  

server: 
  port: 9090





